from typing import Any

def summary(task_dict: dict[str, Any]): ...

def bkgvar3d(task_dict: dict[str, Any]): ...

def lsf(task_dict: dict[str, Any]): ...

def crc_cyl3d(task_dict: dict[str, Any]): ...
